name: tests

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.14'
          - '3.13'
          - '3.12'
          - '3.11'
          - '3.10'
    steps:
    - uses: actions/checkout@v5
    - name: Set up FFmpeg
      run: |
        sudo apt-get -yq update
        sudo apt-get -yq install ffmpeg
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
    - name: Install packages
      run: |
        pip install -r requirements.txt coverage[toml] ruff
    - name: Run linters
      run: |
        ruff check .
        ruff format --check --diff .
    - name: Run test suite
      run: |
        coverage run ./manage.py test
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Run test suite
      run: |
        cd frontend
        npm install
        npm test -- --browsers=ChromeHeadless --code-coverage --watch=false
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
